"""initial

Revision ID: 2d2d716d01fb
Revises: 
Create Date: 2026-05-24 22:46:42.928429
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2d2d716d01fb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
